apiVersion: v1
kind: Service
metadata:
    name: drkiq
spec:
    ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    selector:
        app: drkiq
    type: NodePort
status:
    loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: drkiq
spec:
    selector:
        matchLabels:
            app: drkiq
    replicas: 1
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: drkiq
        spec:
            containers:
            - image: drkiq:v1
              name: drkiq
              env:
              - name: CACHE_URL
                value: redis://redis:6379/0
              - name: DATABASE_URL
                value: postgresql://drkiq:yourpassword@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000
              - name: JOB_WORKER_URL
                value: redis://redis:6379/0
              - name: LISTEN_ON
                value: 0.0.0.0:8000
              - name: SECRET_TOKEN
                value: asecuretokenwouldnormallygohere
              - name: WORKER_PROCESSES
                value: "1"
              ports:
              - containerPort: 8000
              name: drkiq
            restartPolicy: Always
status: {}

