apiVersion: v1
data:
  CACHE_URL: redis://redis:6379/0
  DATABASE_URL: postgresql://drkiq:yourpassword@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000
  JOB_WORKER_URL: redis://redis:6379/0
  LISTEN_ON: 0.0.0.0:8000
  SECRET_TOKEN: asecuretokenwouldnormallygohere
  WORKER_PROCESSES: "1"
kind: ConfigMap
metadata:
  name: drkiq-config
  namespace: default
