apiVersion: v1
kind: Service
metadata:
    name: drkiq
spec:
    ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    selector:
        app: drkiq
    type: NodePort
status:
    loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: drkiq
spec:
    selector:
        matchLabels:
            app: drkiq
    replicas: 1
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: drkiq
        spec:
            containers:
            - image: drkiq:v1
              name: drkiq
              envFrom:
              - configMapRef: 
                    name: drkiq-config
              ports:
              - containerPort: 8000
              name: drkiq
            restartPolicy: Always
status: {}

