apiVersion: v1
kind: PersistentVolume
metadata:
    labels:
        type: local
    name: drkiq-redis-volume
spec:
    storageClassName: manual
    capacity:
        storage: 100Mi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/redisdata"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: drkiq-redis-claim
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
status: {}
