apiVersion: v1
kind: Service
metadata:
    name: postgres
spec:
    ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
    selector:
        app: drkiq
status:
    loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: postgres
spec:
    selector:
        matchLabels:
            app: drkiq
    replicas: 1
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: drkiq
        spec:
            containers:
            - image: postgres:9.4.5
              name: postgres
              env:
              - name: POSTGRES_PASSWORD
                value: yourpassword
              - name: POSTGRES_USER
                value: drkiq
              ports:
              - containerPort: 5432
              name: postgres
              volumeMounts:
              - name: drkiq-postgres
                mountPath: /var/lib/postgresql/data
            volumes:
            - name: drkiq-postgres
              persistentVolumeClaim:
                claimName: drkiq-postgres-claim
            restartPolicy: Always
status: {}
