apiVersion: v1
kind: Service
metadata:
    name: sidekiq
spec:
    ports:
    - name: "55555"
      port: 55555
      targetPort: 55555
    selector:
        app: drkiq
status:
    loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: sidekiq
spec:
    selector:
        matchLabels:
            app: drkiq
    replicas: 1
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: drkiq
        spec:
            containers:
            - image: drkiq:v1
              name: sidekiq
              args: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
              envFrom:
              - configMapRef: 
                    name: drkiq-config
              ports:
              - containerPort: 55555
              name: sidekiq
            restartPolicy: Always
status: {}


